# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.8
    
# what branches should be evaluated
branches:
    only:
        - main

# list of commands to run to setup the environment
install:
    - pip install coverage
    - pip install coveralls


# a list of commands to run before the main script
before_script:
    - python setup.py install

# the actual commands to run
script:
    - coverage run -m unittest discover tests

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls
